name: flutter_helper_cli
description: A Flutter CLI tool for Flutter projects.
version: 0.0.1
homepage: https://github.com/wjdready/flutter_helper_cli

# dart pub global activate --source path .

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  flutter_example:
  flutter_clean:

dependencies:
  path: ^1.9.1
